import React, { createContext, useContext, ReactNode } from 'react';
import { Language, PortfolioContent } from './types';
import { PORTFOLIO_DATA } from './data/portfolio';

// Lab-specific translations interface
export interface LabTranslations {
  title: string;
  uploadTitle: string;
  dragDropText: string;
  maxSize: string;
  analyzing: string;
  confirmIndex: string;
  sessionExpiry: string;
  emptyState: string;
  chatPlaceholder: string;
  detectedLanguage: string;
  dropHere: string;
  fileTypes: string;
  uploading: string;
  processing: string;
  chunksExtracted: string;
  editChunks: string;
  titleLabel: string;
  contentLabel: string;
  rationaleLabel: string;
  confirmSuccess: string;
  errorUpload: string;
  errorProcessing: string;
  errorConfirm: string;
  retry: string;
  cancel: string;
  browseFiles: string;
  dragActive: string;
  sessionInfo: string;
  back: string;
  personalLab: string;
  labDescription: string;
  session24h: string;
  privacyFirst: string;
  geminiAI: string;
  session24hDesc: string;
  privacyFirstDesc: string;
  geminiAIDesc: string;
  chatTitle: string;
  chatWithAgent: string;
  sessionExpiresIn: string;
  hours: string;
  minutes: string;
  and: string;
  retrievedChunks: string;
  chunkTitle: string;
  chunkContent: string;
  noDocumentsYet: string;
  uploadFirst: string;
  thinking: string;
  send: string;
  yourMessage: string;
  errorChat: string;
  collapse: string;
  expand: string;
  startChat: string;
  aiAssistant: string;
  statsTitle: string;
  sessionRequests: string;
  remaining: string;
  analysis: string;
  indexing: string;
  chat: string;
  tokens: string;
  ops: string;
  nearLimitReached: string;
  limitReached: string;
  searchPrecision: string;
  precisionLow: string;
  precisionHigh: string;
  systemContext: string;
  systemContextPlaceholderPl: string;
  systemContextPlaceholderEn: string;
  chunkingStrategy: string;
  chunkingLlm: string;
  chunkingHeuristic: string;
  chunkingLlmDesc: string;
  chunkingHeuristicDesc: string;
}

interface LabContent {
  lab: LabTranslations;
}

const LAB_CONTENT: Record<Language, LabContent> = {
  en: {
    lab: {
      title: 'AI Lab',
      uploadTitle: 'Upload Document',
      dragDropText: 'Drag and drop your file here, or click to browse',
      maxSize: 'Maximum file size: 1MB. Supported formats: .txt, .md, .pdf',
      analyzing: 'Analyzing document...',
      confirmIndex: 'Confirm and Index',
      sessionExpiry: 'Session expires in 24 hours',
      emptyState: 'No documents uploaded yet. Start by uploading a file above.',
      chatPlaceholder: 'Ask about your uploaded documents...',
      detectedLanguage: 'Detected language',
      dropHere: 'Drop file here',
      fileTypes: 'Supported formats',
      uploading: 'Uploading...',
      processing: 'Processing...',
      chunksExtracted: 'Semantic chunks extracted',
      editChunks: 'Edit chunks before indexing',
      titleLabel: 'Title',
      contentLabel: 'Content',
      rationaleLabel: 'Rationale (read-only)',
      confirmSuccess: 'Document indexed successfully!',
      errorUpload: 'Upload failed. Please try again.',
      errorProcessing: 'Processing failed. Please try again.',
      errorConfirm: 'Indexing failed. Please try again.',
      retry: 'Retry',
      cancel: 'Cancel',
      browseFiles: 'Browse files',
      dragActive: 'Release to upload',
      sessionInfo: 'Session',
      back: '← Back',
      personalLab: 'Personal AI Lab',
      labDescription: 'Test private RAG in a secure environment. Your documents, your knowledge base, zero data leakage.',
      session24h: '24-Hour Session',
      privacyFirst: 'Privacy First',
      geminiAI: 'Gemini AI',
      session24hDesc: 'Your data is automatically deleted after 24 hours.',
      privacyFirstDesc: 'Data never leaves the infrastructure. No model training.',
      geminiAIDesc: 'Responses generated by Gemini with your context.',
      chatTitle: 'Lab Chat',
      chatWithAgent: 'Chat with your private AI agent',
      sessionExpiresIn: 'Session expires in',
      hours: 'hours',
      minutes: 'minutes',
      and: 'and',
      retrievedChunks: 'Retrieved Chunks',
      chunkTitle: 'Title',
      chunkContent: 'Content',
      noDocumentsYet: 'No documents uploaded yet',
      uploadFirst: 'Upload documents on the main Lab page to start chatting',
      thinking: 'Thinking...',
      send: 'Send',
      yourMessage: 'Your message',
      errorChat: 'Failed to send message. Please try again.',
      collapse: 'Collapse',
      expand: 'Expand',
      startChat: 'Start Chatting',
      aiAssistant: 'AI Assistant',
      statsTitle: 'Token & Usage Statistics',
      sessionRequests: 'Session Requests',
      remaining: 'remaining',
      analysis: 'Analysis',
      indexing: 'Indexing',
      chat: 'Chat',
      tokens: 'tks',
      ops: 'ops',
      nearLimitReached: 'You are approaching the request limit for this demo session.',
      limitReached: 'Session limit reached. Please wait for the session to expire or contact the administrator.',
      searchPrecision: 'Search precision',
      precisionLow: 'Broad',
      precisionHigh: 'Strict',
      systemContext: 'AI Instructions',
      systemContextPlaceholderPl: 'Jesteś ekspertem w dziedzinie... Odpowiadaj zwięźle i konkretnie.',
      systemContextPlaceholderEn: 'You are an expert in... Answer concisely and specifically.',
      chunkingStrategy: 'Chunking strategy',
      chunkingLlm: 'AI (Gemini)',
      chunkingHeuristic: 'Heuristic',
      chunkingLlmDesc: 'AI analyzes content semantically — best quality, costs tokens',
      chunkingHeuristicDesc: 'Rule-based splitting by headings and paragraphs — free, fast',
    },
  },
  pl: {
    lab: {
      title: 'Laboratorium AI',
      uploadTitle: 'Prześlij Dokument',
      dragDropText: 'Przeciągnij i upuść plik tutaj lub kliknij, aby przeglądać',
      maxSize: 'Maksymalny rozmiar pliku: 1MB. Obsługiwane formaty: .txt, .md, .pdf',
      analyzing: 'Analizowanie dokumentu...',
      confirmIndex: 'Potwierdź i Indeksuj',
      sessionExpiry: 'Sesja wygasa za 24 godziny',
      emptyState: 'Nie przesłano jeszcze dokumentów. Zacznij od przesłania pliku powyżej.',
      chatPlaceholder: 'Zapytaj o przesłane dokumenty...',
      detectedLanguage: 'Wykryty język',
      dropHere: 'Upuść plik tutaj',
      fileTypes: 'Obsługiwane formaty',
      uploading: 'Przesyłanie...',
      processing: 'Przetwarzanie...',
      chunksExtracted: 'Wydobyto fragmenty semantyczne',
      editChunks: 'Edytuj fragmenty przed indeksowaniem',
      titleLabel: 'Tytuł',
      contentLabel: 'Treść',
      rationaleLabel: 'Uzasadnienie (tylko do odczytu)',
      confirmSuccess: 'Dokument zaindeksowany pomyślnie!',
      errorUpload: 'Przesyłanie nie powiodło się. Spróbuj ponownie.',
      errorProcessing: 'Przetwarzanie nie powiodło się. Spróbuj ponownie.',
      errorConfirm: 'Indeksowanie nie powiodło się. Spróbuj ponownie.',
      retry: 'Spróbuj ponownie',
      cancel: 'Anuluj',
      browseFiles: 'Przeglądaj pliki',
      dragActive: 'Upuść, aby przesłać',
      sessionInfo: 'Sesja',
      back: '← Powrót',
      personalLab: 'Osobiste Laboratorium AI',
      labDescription: 'Przetestuj prywatne RAG w bezpiecznym środowisku. Twoje dokumenty, Twoja baza wiedzy, zero wycieków danych.',
      session24h: 'Sesja 24-godzinna',
      privacyFirst: 'Prywatność',
      geminiAI: 'Gemini AI',
      session24hDesc: 'Twoje dane są automatycznie usuwane po 24 godzinach.',
      privacyFirstDesc: 'Dane nie opuszczają infrastruktury. Brak trenowania modeli.',
      geminiAIDesc: 'Odpowiedzi generowane przez Gemini z Twoim kontekstem.',
      chatTitle: 'Czat Lab',
      chatWithAgent: 'Rozmawiaj z prywatnym agentem AI',
      sessionExpiresIn: 'Sesja wygasa za',
      hours: 'godz',
      minutes: 'min',
      and: 'i',
      retrievedChunks: 'Pobrane fragmenty',
      chunkTitle: 'Tytuł',
      chunkContent: 'Treść',
      noDocumentsYet: 'Nie przesłano jeszcze dokumentów',
      uploadFirst: 'Prześlij dokumenty na głównej stronie Lab, aby rozpocząć czat',
      thinking: 'Myślę...',
      send: 'Wyślij',
      yourMessage: 'Twoja wiadomość',
      errorChat: 'Nie udało się wysłać wiadomości. Spróbuj ponownie.',
      collapse: 'Zwiń',
      expand: 'Rozwiń',
      startChat: 'Rozpocznij czat',
      aiAssistant: 'Asystent AI',
      statsTitle: 'Statystyki Zużycia i Tokenów',
      sessionRequests: 'Zapytania w Sesji',
      remaining: 'pozostało',
      analysis: 'Analiza',
      indexing: 'Indeksowanie',
      chat: 'Czat',
      tokens: 'tks',
      ops: 'ops',
      nearLimitReached: 'Zbliżasz się do limitu zapytań dla tej sesji demonstracyjnej.',
      limitReached: 'Osiągnięto limit sesji. Poczekaj na wygaśnięcie sesji lub skontaktuj się z administratorem.',
      searchPrecision: 'Precyzja wyszukiwania',
      precisionLow: 'Szeroko',
      precisionHigh: 'Ściśle',
      systemContext: 'Instrukcje dla AI',
      systemContextPlaceholderPl: 'Jesteś ekspertem w dziedzinie... Odpowiadaj zwięźle i konkretnie.',
      systemContextPlaceholderEn: 'You are an expert in... Answer concisely and specifically.',
      chunkingStrategy: 'Strategia podziału',
      chunkingLlm: 'AI (Gemini)',
      chunkingHeuristic: 'Heurystyczny',
      chunkingLlmDesc: 'AI analizuje treść semantycznie — najlepsza jakość, kosztuje tokeny',
      chunkingHeuristicDesc: 'Podział regułowy po nagłówkach i akapitach — darmowy, szybki',
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  content: PortfolioContent;
  labContent: LabContent;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = React.useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      return (saved === 'pl' || saved === 'en') ? saved : 'en';
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  React.useEffect(() => {
    const saved = localStorage.getItem('language');
    if (!saved) {
      fetch('https://get.geojs.io/v1/ip/country.json')
        .then((res) => res.json())
        .then((data) => {
          if (data.country === 'PL') {
            setLanguage('pl');
          }
        })
        .catch((err) => console.error('Geo-IP check failed:', err));
    }

    const handleStorageChange = () => {
      const savedStorage = localStorage.getItem('language');
      if (savedStorage === 'en' || savedStorage === 'pl') {
        setLanguageState(savedStorage as Language);
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const value = {
    language,
    setLanguage,
    content: PORTFOLIO_DATA[language],
    labContent: LAB_CONTENT[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const useLabTranslations = (): LabTranslations => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLabTranslations must be used within a LanguageProvider');
  }
  return context.labContent.lab;
};
