import React, { createContext, useContext, ReactNode } from 'react';

export type Language = 'en' | 'pl';

// Lab-specific translations interface
export interface LabTranslations {
  title: string;
  uploadTitle: string;
  dragDropText: string;
  maxSize: string;
  analyzing: string;
  confirmIndex: string;
  sessionExpiry: string;
  emptyState: string;
  chatPlaceholder: string;
  detectedLanguage: string;
  // Additional translations for US-014
  dropHere: string;
  fileTypes: string;
  uploading: string;
  processing: string;
  chunksExtracted: string;
  editChunks: string;
  titleLabel: string;
  contentLabel: string;
  rationaleLabel: string;
  confirmSuccess: string;
  errorUpload: string;
  errorProcessing: string;
  errorConfirm: string;
  retry: string;
  cancel: string;
  browseFiles: string;
  dragActive: string;
  sessionInfo: string;
  back: string;
  personalLab: string;
  labDescription: string;
  session24h: string;
  privacyFirst: string;
  geminiAI: string;
  session24hDesc: string;
  privacyFirstDesc: string;
  geminiAIDesc: string;
  // Chat-specific translations for US-015
  chatTitle: string;
  chatWithAgent: string;
  sessionExpiresIn: string;
  hours: string;
  minutes: string;
  and: string;
  retrievedChunks: string;
  chunkTitle: string;
  chunkContent: string;
  noDocumentsYet: string;
  uploadFirst: string;
  thinking: string;
  send: string;
  yourMessage: string;
  errorChat: string;
  collapse: string;
  expand: string;
  startChat: string;
  aiAssistant: string;
}

// Complete translations object for Lab feature
interface LabContent {
  lab: LabTranslations;
}

const LAB_CONTENT: Record<Language, LabContent> = {
  en: {
    lab: {
      title: 'AI Lab',
      uploadTitle: 'Upload Document',
      dragDropText: 'Drag and drop your file here, or click to browse',
      maxSize: 'Maximum file size: 10MB. Supported formats: .txt, .md, .pdf',
      analyzing: 'Analyzing document...',
      confirmIndex: 'Confirm and Index',
      sessionExpiry: 'Session expires in 24 hours',
      emptyState: 'No documents uploaded yet. Start by uploading a file above.',
      chatPlaceholder: 'Ask about your uploaded documents...',
      detectedLanguage: 'Detected language',
      // Additional translations for US-014
      dropHere: 'Drop file here',
      fileTypes: 'Supported formats',
      uploading: 'Uploading...',
      processing: 'Processing...',
      chunksExtracted: 'Semantic chunks extracted',
      editChunks: 'Edit chunks before indexing',
      titleLabel: 'Title',
      contentLabel: 'Content',
      rationaleLabel: 'Rationale (read-only)',
      confirmSuccess: 'Document indexed successfully!',
      errorUpload: 'Upload failed. Please try again.',
      errorProcessing: 'Processing failed. Please try again.',
      errorConfirm: 'Indexing failed. Please try again.',
      retry: 'Retry',
      cancel: 'Cancel',
      browseFiles: 'Browse files',
      dragActive: 'Release to upload',
      sessionInfo: 'Session',
      back: '← Back',
      personalLab: 'Personal AI Lab',
      labDescription: 'Test private RAG in a secure environment. Your documents, your knowledge base, zero data leakage.',
      session24h: '24-Hour Session',
      privacyFirst: 'Privacy First',
      geminiAI: 'Gemini AI',
      session24hDesc: 'Your data is automatically deleted after 24 hours.',
      privacyFirstDesc: 'Data never leaves the infrastructure. No model training.',
      geminiAIDesc: 'Responses generated by Gemini with your context.',
      // Chat-specific translations for US-015
      chatTitle: 'Lab Chat',
      chatWithAgent: 'Chat with your private AI agent',
      sessionExpiresIn: 'Session expires in',
      hours: 'hours',
      minutes: 'minutes',
      and: 'and',
      retrievedChunks: 'Retrieved Chunks',
      chunkTitle: 'Title',
      chunkContent: 'Content',
      noDocumentsYet: 'No documents uploaded yet',
      uploadFirst: 'Upload documents on the main Lab page to start chatting',
      thinking: 'Thinking...',
      send: 'Send',
      yourMessage: 'Your message',
      errorChat: 'Failed to send message. Please try again.',
      collapse: 'Collapse',
      expand: 'Expand',
      startChat: 'Start Chatting',
      aiAssistant: 'AI Assistant',
    },
  },
  pl: {
    lab: {
      title: 'Laboratorium AI',
      uploadTitle: 'Prześlij Dokument',
      dragDropText: 'Przeciągnij i upuść plik tutaj lub kliknij, aby przeglądać',
      maxSize: 'Maksymalny rozmiar pliku: 10MB. Obsługiwane formaty: .txt, .md, .pdf',
      analyzing: 'Analizowanie dokumentu...',
      confirmIndex: 'Potwierdź i Indeksuj',
      sessionExpiry: 'Sesja wygasa za 24 godziny',
      emptyState: 'Nie przesłano jeszcze dokumentów. Zacznij od przesłania pliku powyżej.',
      chatPlaceholder: 'Zapytaj o przesłane dokumenty...',
      detectedLanguage: 'Wykryty język',
      // Additional translations for US-014
      dropHere: 'Upuść plik tutaj',
      fileTypes: 'Obsługiwane formaty',
      uploading: 'Przesyłanie...',
      processing: 'Przetwarzanie...',
      chunksExtracted: 'Wydobyto fragmenty semantyczne',
      editChunks: 'Edytuj fragmenty przed indeksowaniem',
      titleLabel: 'Tytuł',
      contentLabel: 'Treść',
      rationaleLabel: 'Uzasadnienie (tylko do odczytu)',
      confirmSuccess: 'Dokument zaindeksowany pomyślnie!',
      errorUpload: 'Przesyłanie nie powiodło się. Spróbuj ponownie.',
      errorProcessing: 'Przetwarzanie nie powiodło się. Spróbuj ponownie.',
      errorConfirm: 'Indeksowanie nie powiodło się. Spróbuj ponownie.',
      retry: 'Spróbuj ponownie',
      cancel: 'Anuluj',
      browseFiles: 'Przeglądaj pliki',
      dragActive: 'Upuść, aby przesłać',
      sessionInfo: 'Sesja',
      back: '← Powrót',
      personalLab: 'Osobiste Laboratorium AI',
      labDescription: 'Przetestuj prywatne RAG w bezpiecznym środowisku. Twoje dokumenty, Twoja baza wiedzy, zero wycieków danych.',
      session24h: 'Sesja 24-godzinna',
      privacyFirst: 'Prywatność',
      geminiAI: 'Gemini AI',
      session24hDesc: 'Twoje dane są automatycznie usuwane po 24 godzinach.',
      privacyFirstDesc: 'Dane nie opuszczają infrastruktury. Brak trenowania modeli.',
      geminiAIDesc: 'Odpowiedzi generowane przez Gemini z Twoim kontekstem.',
      // Chat-specific translations for US-015
      chatTitle: 'Czat Lab',
      chatWithAgent: 'Rozmawiaj z prywatnym agentem AI',
      sessionExpiresIn: 'Sesja wygasa za',
      hours: 'godz',
      minutes: 'min',
      and: 'i',
      retrievedChunks: 'Pobrane fragmenty',
      chunkTitle: 'Tytuł',
      chunkContent: 'Treść',
      noDocumentsYet: 'Nie przesłano jeszcze dokumentów',
      uploadFirst: 'Prześlij dokumenty na głównej stronie Lab, aby rozpocząć czat',
      thinking: 'Myślę...',
      send: 'Wyślij',
      yourMessage: 'Twoja wiadomość',
      errorChat: 'Nie udało się wysłać wiadomości. Spróbuj ponownie.',
      collapse: 'Zwiń',
      expand: 'Rozwiń',
      startChat: 'Rozpocznij czat',
      aiAssistant: 'Asystent AI',
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  content: LabContent;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Get language from parent context/localStorage or default to 'en'
  const [language, setLanguageState] = React.useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      return saved === 'pl' ? 'pl' : 'en';
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  // Sync with storage changes and handle initial detection
  React.useEffect(() => {
    const saved = localStorage.getItem('language');
    if (!saved) {
      fetch('https://get.geojs.io/v1/ip/country.json')
        .then((res) => res.json())
        .then((data) => {
          if (data.country === 'PL') {
            setLanguage('pl');
          }
        })
        .catch((err) => console.error('Geo-IP check failed:', err));
    }

    const handleStorageChange = () => {
      const savedStorage = localStorage.getItem('language');
      if (savedStorage === 'en' || savedStorage === 'pl') {
        setLanguageState(savedStorage as Language);
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const value = {
    language,
    setLanguage,
    content: LAB_CONTENT[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// General language hook
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Type-safe hook specifically for Lab translations
export const useLabTranslations = (): LabTranslations => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLabTranslations must be used within a LanguageProvider');
  }
  return context.content.lab;
};

// Utility to get raw translation value by key (for dynamic access)
export const getLabTranslation = (
  language: Language,
  key: keyof LabTranslations
): string => {
  return LAB_CONTENT[language].lab[key];
};
