import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../core/auth/AuthContext';
import { useLanguage } from '../LanguageContext';
import { Beaker, Clock, Shield, FileText, Brain, ArrowRight } from 'lucide-react';

const LabPage: React.FC = () => {
  const { user, loading } = useAuth();
  const { content, language } = useLanguage();
  const navigate = useNavigate();

  useEffect(() => {
    if (!loading && !user) {
      // Redirect to home if not authenticated
      navigate('/');
    }
  }, [user, loading, navigate]);

  if (loading) {
    return (
      <div className="min-h-screen bg-dark flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (!user) {
    return null;
  }

  return (
    <div className="min-h-screen bg-dark text-white">
      {/* Header */}
      <nav className="fixed top-0 left-0 right-0 z-40 backdrop-blur-md bg-darker/80 border-b border-slate-800 h-16 flex items-center justify-between px-6 lg:px-24">
        <a href="/" className="font-mono font-bold text-xl text-white tracking-tighter hover:text-primary transition-colors">
          ks-infra<span className="text-primary">.dev</span>
        </a>
        <div className="flex items-center gap-4">
          <span className="text-xs text-slate-400 font-mono">
            {language === 'pl' ? 'Sesja: 24h' : 'Session: 24h'}
          </span>
          <a 
            href="/"
            className="text-sm text-slate-300 hover:text-primary transition-colors"
          >
            {language === 'pl' ? '← Powrót' : '← Back'}
          </a>
        </div>
      </nav>

      {/* Main Content */}
      <main className="pt-24 pb-16 px-6 lg:px-24 max-w-7xl mx-auto">
        {/* Hero Section */}
        <div className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <Beaker className="text-primary" size={28} />
            <h1 className="text-3xl md:text-4xl font-bold text-white">
              {language === 'pl' ? 'Osobiste Laboratorium AI' : 'Personal AI Lab'}
            </h1>
          </div>
          <p className="text-slate-400 text-lg max-w-2xl">
            {language === 'pl' 
              ? 'Przetestuj prywatne RAG w bezpiecznym środowisku. Twoje dokumenty, Twoja baza wiedzy, zero wycieków danych.'
              : 'Test private RAG in a secure environment. Your documents, your knowledge base, zero data leakage.'}
          </p>
        </div>

        {/* Info Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-12">
          <div className="bg-surface/50 border border-slate-700 p-6 rounded-sm">
            <Clock className="text-primary mb-3" size={24} />
            <h3 className="text-white font-bold mb-2">
              {language === 'pl' ? 'Sesja 24-godzinna' : '24-Hour Session'}
            </h3>
            <p className="text-slate-400 text-sm">
              {language === 'pl' 
                ? 'Twoje dane są automatycznie usuwane po 24 godzinach.'
                : 'Your data is automatically deleted after 24 hours.'}
            </p>
          </div>
          <div className="bg-surface/50 border border-slate-700 p-6 rounded-sm">
            <Shield className="text-primary mb-3" size={24} />
            <h3 className="text-white font-bold mb-2">
              {language === 'pl' ? 'Prywatność' : 'Privacy First'}
            </h3>
            <p className="text-slate-400 text-sm">
              {language === 'pl'
                ? 'Dane nie opuszczają infrastruktury. Brak trenowania modeli.'
                : 'Data never leaves the infrastructure. No model training.'}
            </p>
          </div>
          <div className="bg-surface/50 border border-slate-700 p-6 rounded-sm">
            <Brain className="text-primary mb-3" size={24} />
            <h3 className="text-white font-bold mb-2">
              {language === 'pl' ? 'Gemini AI' : 'Gemini AI'}
            </h3>
            <p className="text-slate-400 text-sm">
              {language === 'pl'
                ? 'Odpowiedzi generowane przez Gemini z Twoim kontekstem.'
                : 'Responses generated by Gemini with your context.'}
            </p>
          </div>
        </div>

        {/* Upload Section */}
        <div className="bg-surface border border-slate-700 rounded-sm p-8">
          <div className="flex items-center gap-3 mb-6">
            <FileText className="text-primary" size={24} />
            <h2 className="text-xl font-bold text-white">
              {language === 'pl' ? 'Prześlij Dokumenty' : 'Upload Documents'}
            </h2>
          </div>
          
          <div className="border-2 border-dashed border-slate-600 rounded-sm p-12 text-center hover:border-primary/50 transition-colors">
            <div className="max-w-md mx-auto">
              <p className="text-slate-400 mb-4">
                {language === 'pl'
                  ? 'Funkcjonalność uploadu będzie dostępna wkrótce. Obecnie trwają prace nad backendem.'
                  : 'Upload functionality coming soon. Backend work in progress.'}
              </p>
              <span className="inline-flex items-center gap-2 text-primary text-sm">
                {language === 'pl' ? 'Dostępne formaty' : 'Supported formats'}: .txt, .md, .pdf
              </span>
            </div>
          </div>
        </div>

        {/* Session Info */}
        <div className="mt-8 p-4 bg-primary/5 border border-primary/20 rounded-sm">
          <div className="flex items-center gap-2 text-primary text-sm">
            <ArrowRight size={16} />
            <span className="font-mono">
              {language === 'pl' 
                ? `UID: ${user.uid.slice(0, 8)}... | Język: ${language.toUpperCase()}`
                : `UID: ${user.uid.slice(0, 8)}... | Language: ${language.toUpperCase()}`}
            </span>
          </div>
        </div>
      </main>
    </div>
  );
};

export default LabPage;
